### ISSUE TITLE
showing how to set state in ES7 lacks code context

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/react-component-mounting-lifecycle-readme#3]
add more code context around showing how state can be set in ES7

Current:

```
state = {
  key: "value"
}
```

Proposing:

```
class MyComponent extends Component {
  state = {
    key: "value"
  }
  constructor() { /* ... */ }
}
```

Or, more minimally:

```
class Foo {
  state = {}
}
```

**Comment by maxwellbenton** [comment]
Hey @geluso,

I've added class syntax around both the constructor and ES7 versions of setting state, which should resolve this issue and help prevent confusion in the future.

Thank you for spotting this and providing feedback!
